version: '3.7'

services: 
    app-server:
        build: 
            context: simple-note-server
            dockerfile: Dockerfile
        ports: 
            - "9000:9000"
        restart: always
        depends_on: 
            - db
        environment: 
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simple-note
            SPRING_DATASOURCE_USERNAME: alexandernsalim
            SPRING_DATASOURCE_PASSWORD: alexandernsalim
            SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/simple-note
            SPRING_FLYWAY_USER: alexandernsalim
            SPRING_FLYWAY_PASSWORD: alexandernsalim
        networks: 
            - backend
            - frontend

    app-client:
        build: 
            context: simple-note-client
            dockerfile: Dockerfile
        ports: 
            - "8080:80"
        restart: always
        depends_on: 
            - app-server
        networks:
            - frontend
    
    db:
        image: postgres:11.9-alpine
        expose: 
            - 5432
        ports: 
            - "5432:5432"
        restart: always
        environment: 
            POSTGRES_DB: simple-note
            POSTGRES_USER: alexandernsalim
            POSTGRES_PASSWORD: alexandernsalim
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks: 
            - backend

volumes:
    postgres-data:

networks: 
    backend:
    frontend: